// Every user-facing string of the admin lives here (decision 17).
// Plain French, tutoiement, buttons are verbs, messages are information. No aphorism,
// no slogan, no sentence built on a negated opposite ("X, pas Y"), no em dash.
// The writing rules and the checklist are in docs/STRINGS.md.

export const fr = {
  app: {
    nom: 'LEQ',
    sousTitre: 'Espace de Rebecca',
  },

  commun: {
    chargement: 'Chargement en cours.',
    reessayer: 'Réessayer',
    enregistrer: 'Enregistrer',
    annuler: 'Annuler',
    continuer: 'Continuer',
    fermer: 'Fermer',
    modifieLe: (date: string) => `Modifié le ${date}`,
    oui: 'Oui',
    non: 'Non',
  },

  navigation: {
    libelle: 'Navigation principale',
    accueil: 'Accueil',
    configuration: 'Configuration',
    drapeaux: 'Drapeaux',
    defis: 'Défis',
    exercices: 'Exercices',
    recompenses: 'Récompenses',
    echanges: 'Échanges',
    grille: 'Grille',
    annonces: 'Annonces',
    ateliers: 'Ateliers',
    sujets: "Sujets de l'Arène",
    theses: 'Thèses du face-à-face',
    moderation: 'Modération',
    utilisateurs: 'Utilisateurs',
    exports: 'Demandes de données',
    seDeconnecter: 'Se déconnecter',
  },

  connexion: {
    titre: 'Se connecter',
    intro: 'Connecte-toi avec ton adresse e-mail et ton mot de passe.',
    email: 'Adresse e-mail',
    motDePasse: 'Mot de passe',
    valider: 'Se connecter',
    enCours: 'Connexion en cours',
    identifiantsIncorrects: 'Identifiants incorrects.',
    indisponible: 'Connexion impossible pour le moment. Réessaie dans un instant.',
  },

  acces: {
    reserve: 'Cet espace est réservé à Rebecca.',
    connecteAvec: (email: string) => `Tu es connecté·e avec ${email}.`,
    verification: 'Vérification de ta session.',
  },

  accueil: {
    titre: 'Accueil',
    intro:
      "Ici, tu règles l'application : ses valeurs, et ce qui est visible pour les utilisateurs.",
    disponible: 'Disponible maintenant',
    bientot: 'Bientôt',
    aVenirIntro: "D'autres espaces arriveront plus tard.",
    cartes: {
      configuration: {
        titre: 'Configuration',
        texte: "Les valeurs de l'application : points, durées, quotas, délais.",
        action: 'Ouvrir la configuration',
      },
      drapeaux: {
        titre: 'Drapeaux',
        texte: "Allumer ou éteindre l'Arène, les duels et le face-à-face.",
        action: 'Ouvrir les drapeaux',
      },
      defis: {
        titre: 'Les défis',
        texte: 'Les étapes du parcours, acte par acte : formats, consignes, seuils de réussite.',
        action: 'Ouvrir les défis',
      },
      exercices: {
        titre: 'Les exercices',
        texte: 'Les exercices de rattrapage, proposés après deux échecs sur un défi.',
        action: 'Ouvrir les exercices',
      },
      recompenses: {
        titre: 'Les récompenses',
        texte: 'La boutique : ce que les points achètent, à quel prix, et combien par mois.',
        action: 'Ouvrir les récompenses',
      },
      echanges: {
        titre: 'Les échanges',
        texte: 'Les points échangés par les utilisateurs, à honorer ou à annuler.',
        action: 'Ouvrir les échanges',
      },
      grille: {
        titre: 'La grille',
        texte:
          'Tes critères, versionnés : chaque nouvelle prise est notée avec la version publiée.',
        action: 'Ouvrir la grille',
      },
      annonces: {
        titre: 'Les annonces',
        texte: 'Un message à toute la base ou à des régions, deux par mois au plus.',
        action: 'Ouvrir les annonces',
      },
      ateliers: {
        titre: 'Les ateliers',
        texte: "Tes ateliers, en salle ou en ligne, tels que l'application les montre.",
        action: 'Ouvrir les ateliers',
      },
      theses: {
        titre: 'Les thèses du face-à-face',
        texte: 'La banque des sujets de débat, proposés en premier à qui veut débattre.',
        action: 'Ouvrir la banque de thèses',
      },
      sujets: {
        titre: "Les sujets de l'Arène",
        texte: 'La banque des sujets, dans leur ordre de passage. Un par semaine.',
        action: 'Ouvrir les sujets',
      },
      moderation: {
        titre: 'La modération',
        texte: 'Les prises publiques à relire avant publication, et celles à retirer.',
        action: 'Ouvrir la modération',
      },
      utilisateurs: {
        titre: 'Les utilisateurs',
        texte: 'Les profils, la suspension et la réactivation.',
        action: 'Ouvrir les utilisateurs',
      },
      exports: {
        titre: 'Les demandes de données',
        texte: 'Les personnes qui veulent une copie de leurs données, à traiter par e-mail.',
        action: 'Ouvrir les demandes',
      },
    },
    aVenir: {
      banques: {
        titre: 'Les banques de sujets',
        texte: "Sujets de l'Arène, thèses du face-à-face.",
      },
    },
  },

  configuration: {
    titre: 'Configuration',
    intro:
      "Chaque valeur est lue par l'application au démarrage. Un changement s'applique aux prochains lancements.",
    colonnes: {
      cle: 'Clé',
      description: 'Description',
      valeur: 'Valeur',
      actions: 'Actions',
    },
    sections: {
      points: 'Points',
      diagnostic: 'Diagnostic',
      parcours: 'Rythme du parcours',
      serie: 'Série et points',
      arene: 'Arène et duels',
      faceAFace: 'Face-à-face',
      annonces: 'Annonces',
      nettoyage: 'Nettoyage',
      autres: 'Autres',
    },
    vide: 'Aucune valeur dans la base. Lance la migration et le seed.',
    erreurChargement: 'Impossible de charger la configuration.',
    erreurs: {
      nombre: 'Saisis un nombre.',
      vide: 'Saisis une valeur.',
      json: 'JSON invalide.',
    },
    etats: {
      modifie: 'Modifié, pas encore enregistré.',
      enregistrement: 'Enregistrement',
    },
    toasts: {
      succes: (cle: string) => `Valeur enregistrée : ${cle}.`,
      erreur: 'Enregistrement impossible. La valeur précédente est rétablie.',
    },
    champ: {
      valeurDe: (cle: string) => `Valeur de ${cle}`,
      annulerPour: (cle: string) => `Annuler les changements de ${cle}`,
      enregistrerPour: (cle: string) => `Enregistrer ${cle}`,
    },
  },

  drapeaux: {
    titre: 'Drapeaux',
    intro:
      'Un drapeau allumé rend la fonction visible à tous les utilisateurs dès leur prochain lancement.',
    vide: 'Aucun drapeau dans la base. Lance la migration et le seed.',
    erreurChargement: 'Impossible de charger les drapeaux.',
    etats: {
      allume: 'Allumé',
      eteint: 'Éteint',
      absent: 'Absent de la base',
    },
    basculer: (objet: string) => `Allumer ou éteindre ${objet}`,
    confirmationTitre: (objet: string) => `Allumer ${objet}`,
    items: {
      arene: {
        nom: "L'Arène",
        objet: "l'Arène",
        description: 'Le sujet de la semaine, les prises publiques et les votes.',
        confirmation: "Allumer l'Arène la rend visible à tous les utilisateurs. Continuer ?",
      },
      duels: {
        nom: 'Les duels',
        objet: 'les duels',
        description: "Les défis entre deux personnes, avec un verdict rendu par l'analyse.",
        confirmation: 'Allumer les duels les rend visibles à tous les utilisateurs. Continuer ?',
      },
      face_a_face: {
        nom: 'Le face-à-face',
        objet: 'le face-à-face',
        description: 'Le débat en direct avec Rétor.',
        confirmation: 'Allumer le face-à-face le rend visible à tous les utilisateurs. Continuer ?',
      },
    },
    toasts: {
      succes: 'Enregistré.',
      erreur: "Enregistrement impossible. L'état précédent est rétabli.",
    },
  },

  banques: {
    formats: {
      standard: 'Défi',
      texte: 'Défi texte',
      long: 'Grand format',
    },
    badges: {
      provisoire: 'Provisoire',
      valide: 'Validé',
      inactif: 'Inactif',
    },
    erreurs: {
      requis: 'Ce champ est obligatoire.',
      nombre: 'Saisis un nombre.',
      entier: 'Saisis un nombre entier.',
      positif: 'Saisis un nombre positif.',
      cle: 'Lettres minuscules, chiffres et tirets bas seulement.',
      texteRequis: 'Un défi texte a besoin de son texte à lire.',
      preparationRequise: 'Un grand format a besoin de sa durée de préparation.',
      bande: 'Le max doit être supérieur ou égal au min.',
      contrat: 'Cette valeur ne respecte pas le contrat.',
    },
    champs: {
      cle: 'Clé technique',
      cleAide: 'Unique, en minuscules, sans espace : elle ne change plus après la création.',
      titre: 'Titre',
      consigne: 'Consigne',
      consigneAide: 'Ce que la personne lit avant de parler, dans tes mots.',
      competence: 'Compétence travaillée',
      competenceAide: 'Le même mot relie un défi et ses exercices de rattrapage.',
      provisoire: 'Provisoire',
      provisoireAide:
        "Tant que c'est coché, l'application dit que la consigne attend Rebecca. Décoche quand le texte est le tien.",
      actif: 'Actif',
      actifAide: "Un défi inactif n'entre plus dans les nouveaux parcours.",
      actifAideExercice: "Un exercice inactif n'est plus proposé.",
    },
  },

  defis: {
    titre: 'Les défis',
    intro:
      "Le parcours, acte par acte. Un titre ou une consigne modifiée s'affiche tout de suite pour tout le monde ; l'ordre et le seuil de réussite s'appliquent aux parcours créés ensuite.",
    creer: 'Créer un défi',
    vide: 'Aucun défi dans la base. Lance le seed, ou crée le premier.',
    erreurChargement: 'Impossible de charger les défis.',
    acte: (ordre: number) => `Acte ${ordre}`,
    nombreDefis: (n: number) => (n === 1 ? '1 défi' : `${n} défis`),
    aucunDefi: 'Aucun défi dans cet acte.',
    renommer: 'Renommer',
    ajouterActe: 'Ajouter un acte',
    acteTitre: "Titre de l'acte",
    acteSousTitre: 'Sous-titre',
    acteEnregistre: 'Acte enregistré.',
    monter: (titre: string) => `Monter ${titre}`,
    descendre: (titre: string) => `Descendre ${titre}`,
    modifier: 'Modifier',
    resume: (minutes: number, points: number) => `${minutes} min · ${points} pts`,
    seuil: (seuil: string) => `seuil ${seuil}`,
    ordreEchange: 'Ordre modifié.',
    erreurOrdre: "L'ordre n'a pas pu être modifié.",
    edition: {
      titreCreation: 'Nouveau défi',
      titreModification: 'Modifier le défi',
      introuvable: "Ce défi n'existe pas.",
      retour: 'Retour aux défis',
      acte: 'Acte',
      ordre: "Ordre dans l'acte",
      format: 'Format',
      formatAide:
        'Défi : deux minutes de parole. Défi texte : un texte à lire, puis à défendre. Grand format : une préparation, puis cinq minutes.',
      focus: 'Ce que le retour regardera',
      focusAide: 'Annoncé dans le brief : « Le retour regardera : … ». Un seul point à la fois.',
      dureeMax: 'Durée maximale de parole',
      points: 'Points',
      seuil: 'Seuil de réussite',
      seuilAide: 'Note totale de la grille à atteindre. Sans grille publiée, le défi reste ouvert.',
      texte: 'Le texte à lire',
      dureeLecture: 'Durée de lecture estimée',
      preparation: 'Durée de préparation',
      plan: 'Les appuis du plan',
      planAide: 'Affichés pendant la préparation et la prise. Trois, en général.',
      appuiTitre: "Titre de l'appui",
      appuiDetail: 'Détail',
      ajouterAppui: 'Ajouter un appui',
      retirerAppui: (n: number) => `Retirer l'appui ${n}`,
      secondes: 's',
      marquerValide: 'Marquer comme validé',
      marquerValideTitre: 'Marquer ce défi comme validé',
      marquerValideMessage:
        "L'application cessera de dire que la consigne est provisoire. Vérifie que le texte est bien le tien. Continuer ?",
      desactiver: 'Désactiver',
      desactiverTitre: 'Désactiver ce défi',
      desactiverMessage:
        "Il n'entrera plus dans les nouveaux parcours. Les personnes qui l'ont déjà dans leur chemin le gardent. Continuer ?",
      reactiver: 'Réactiver',
      cree: 'Défi créé.',
      enregistre: 'Défi enregistré.',
      erreur: 'Enregistrement impossible.',
      erreurDoublon: 'Un défi porte déjà cette clé, ou cet ordre dans cet acte.',
    },
  },

  exercices: {
    titre: 'Les exercices',
    intro:
      'Les exercices de rattrapage : après deux échecs sur un défi, la personne se voit proposer le premier exercice actif de la même compétence, avant un troisième essai.',
    creer: 'Créer un exercice',
    vide: 'Aucun exercice dans la base. Lance le seed, ou crée le premier.',
    erreurChargement: 'Impossible de charger les exercices.',
    duree: (secondes: number) => `${secondes} s`,
    competence: (competence: string) => `compétence : ${competence}`,
    modifier: 'Modifier',
    nouveau: 'Nouvel exercice',
    modification: "Modifier l'exercice",
    dureeChamp: 'Durée',
    cree: 'Exercice créé.',
    enregistre: 'Exercice enregistré.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Un exercice porte déjà cette clé.',
  },

  recompenses: {
    titre: 'Les récompenses',
    intro:
      "La boutique du chapitre 7. Un coût en points par récompense ; un plafond par mois pour ce qui te coûte de l'argent réel : au-delà, elle attend le mois suivant. Une distinction ne s'achète pas.",
    creer: 'Créer une récompense',
    nouvelle: 'Nouvelle récompense',
    vide: 'Aucune récompense dans la base. Lance le seed, ou crée la première.',
    erreurChargement: 'Impossible de charger les récompenses.',
    modifier: 'Modifier',
    cout: (points: number) => `${new Intl.NumberFormat('fr-FR').format(points)} pts`,
    sansCout: 'sans coût',
    plafond: (n: number) => (n === 1 ? '1 par mois' : `${n} par mois`),
    sansPlafond: 'sans plafond',
    cree: 'Récompense créée.',
    enregistre: 'Récompense enregistrée.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Une récompense porte déjà cette clé.',
    champs: {
      type: 'Type',
      typeAide:
        "Contenu, réduction, atelier : s'échangent contre des points. Distinction : attribuée, sans coût en points.",
      ordre: 'Ordre dans la boutique',
      sousTitre: 'Sous-titre',
      description: 'Description',
      cout: 'Coût en points',
      plafond: 'Plafond par mois',
      plafondAide: "Vide = sans limite. À remplir dès que la récompense te coûte de l'argent réel.",
      distinctionAide:
        "Une distinction n'a ni coût ni plafond : elle se gagne, par exemple pour le n°1 du mois.",
      provisoireAide: "Tant que c'est coché, l'application dit que la récompense attend Rebecca.",
      actifAide: "Une récompense inactive n'apparaît plus dans la boutique.",
    },
  },

  echanges: {
    titre: 'Les échanges',
    intro:
      "Chaque ligne est une personne qui a dépensé ses points. Honorer : tu l'as contactée et la récompense est donnée. Annuler : les points lui reviennent.",
    tous: 'Tous',
    vide: 'Aucun échange dans cette liste.',
    erreurChargement: 'Impossible de charger les échanges.',
    par: (prenom: string) => `par ${prenom}`,
    sansPrenom: 'une personne sans prénom',
    honorer: 'Honorer',
    annuler: 'Annuler',
    annulerTitre: 'Annuler cet échange',
    annulerMessage: (titre: string, points: number) =>
      `${titre} : les ${new Intl.NumberFormat('fr-FR').format(points)} points reviennent à la personne. Continuer ?`,
    traite: 'Échange mis à jour.',
    erreur: "L'échange n'a pas pu être mis à jour.",
    statuts: {
      a_traiter: 'À traiter',
      honore: 'Honoré',
      annule: 'Annulé',
    },
  },

  grille: {
    titre: 'La grille',
    intro:
      'Ta grille, en versions. Un brouillon se modifie critère par critère ; une fois publiée, une version ne bouge plus et chaque nouvelle prise est notée avec la version publiée la plus récente. Les prises déjà notées gardent leur version.',
    vide: 'Aucune version. Crée la première pour écrire tes critères.',
    erreurChargement: 'Impossible de charger la grille.',
    erreur: 'Enregistrement impossible.',
    premiereVersion: 'Créer la première version',
    nouvelleVersionDepuis: (v: number) => `Nouvelle version à partir de la ${v}`,
    version: (v: number) => `Version ${v}`,
    versionCreee: (v: number) => `Version ${v} créée, en brouillon.`,
    publieeLe: (date: string) => `publiée le ${date}`,
    publieeCourte: 'Publiée',
    brouillon: 'Brouillon',
    enService: 'En service pour les nouvelles prises',
    nbCriteres: (n: number) => (n === 1 ? '1 critère' : `${n} critères`),
    nbElements: (n: number) => (n === 1 ? '1 mesure' : `${n} mesures`),
    surMax: (max: number) => `sur ${max}`,
    lectureSeule:
      'Cette version est publiée : elle ne se modifie plus. Crée une nouvelle version pour changer un critère.',
    ajouterCritere: 'Ajouter un critère',
    aucunCritere: 'Aucun critère dans cette version.',
    modifier: 'Modifier',
    supprimer: 'Supprimer',
    supprimerTitre: (nom: string) => `Supprimer le critère « ${nom} »`,
    supprimerMessage:
      'Il disparaît de ce brouillon. Les versions publiées ne changent pas. Continuer ?',
    publier: 'Publier cette version',
    publierTitre: (v: number) => `Publier la version ${v}`,
    publierMessage:
      'À partir de maintenant, chaque nouvelle prise est notée avec cette version et le défi du jour se valide sur ses notes. Une version publiée ne se dépublie pas : pour changer, crée une nouvelle version. Continuer ?',
    publiee: 'Version publiée. Elle note les prochaines prises.',
    critereEnregistre: 'Critère enregistré.',
    critereSupprime: 'Critère supprimé.',
    champs: {
      cle: 'Clé technique',
      cleAide: 'Minuscules, chiffres, tirets bas. Elle nomme la sous-note dans chaque retour.',
      nom: 'Nom montré',
      scoreMax: 'Note maximale',
      scoreMaxAide: 'La somme des notes maximales des critères fait la note totale de la grille.',
      definition: 'Définition',
      definitionAide: 'Ce que le critère écoute, en une phrase. Montré à côté du nom.',
      elements: 'Les mesures écoutées',
      elementsAide:
        "Chaque mesure lit un chiffre de l'analyse et le range dans une bande ; la note du critère est la moyenne pondérée des bandes, ramenée à la note maximale.",
      mesure: 'Mesure',
      mesureAide: "Un chemin dans les mesures de l'analyse (docs/DATA-MODEL.md).",
      parType: 'un mot béquille précis…',
      mot: 'Le mot',
      poids: 'Poids',
      poidsAide: "Une mesure de poids 2 compte deux fois plus qu'une mesure de poids 1.",
      bandes: 'Les bandes',
      bandesAide:
        'De min (inclus) à max (exclu) : la note de la bande. Laisse min ou max vide pour une bande ouverte. Une valeur hors de toute bande vaut 0.',
      min: 'min',
      max: 'max',
      score: 'note',
      ajouterBande: 'Ajouter une bande',
      retirerBande: (n: number) => `Retirer la bande ${n}`,
      ajouterElement: 'Ajouter une mesure',
      retirerElement: 'Retirer cette mesure',
    },
  },

  annonces: {
    titre: 'Les annonces',
    intro:
      "Un message poussé sur les téléphones des personnes qui gardent l'interrupteur allumé. Deux par mois au plus, comptées sur l'ensemble de la base ; choisis des régions pour un atelier en salle, aucune pour un atelier en ligne.",
    compteur: (n: number, plafond: number) => `${n} sur ${plafond} ce mois-ci`,
    envoyer: 'Envoyer maintenant',
    envoyee: 'Annonce envoyée. Le serveur la pousse dans les prochaines minutes.',
    plafondAtteint:
      'Le plafond du mois est atteint. La prochaine annonce attendra le mois prochain.',
    erreur: "L'annonce n'a pas été envoyée.",
    erreurChamp: 'Vérifie ce champ.',
    erreurChargement: 'Impossible de charger les annonces.',
    historique: 'Envoyées',
    vide: 'Aucune annonce envoyée pour le moment.',
    toutLeMonde: 'Tout le monde',
    nbRegions: (n: number) => (n === 1 ? '1 région' : `${n} régions`),
    enCours: 'Envoi en cours',
    bilan: (envoyes: number, destinataires: number, echecs: number) =>
      echecs === 0
        ? `${envoyes} sur ${destinataires} reçues`
        : `${envoyes} sur ${destinataires} reçues, ${echecs} en échec`,
    champs: {
      titre: 'Titre',
      titreAide:
        'Court : il tient sur un écran verrouillé. Exemple : « Rebecca ouvre un atelier ».',
      corps: 'Message',
      corpsAide: "L'atelier, la date et les places, sur le ton d'une invitation.",
      atelier: 'Atelier lié',
      atelierAide:
        "Optionnel : l'application ouvre sa fiche quand la personne touche la notification.",
      sansAtelier: 'Aucun',
      regions: 'Régions',
      regionsAide:
        'Aucune région cochée : tout le monde. Un atelier en salle : sa région et les voisines.',
    },
  },

  ateliers: {
    titre: 'Les ateliers',
    intro:
      "Ce que l'application montre dans « Avec Rebecca, ce mois-ci » et sur l'écran qui te présente. Un atelier publié est visible ; un brouillon ne l'est pas.",
    creer: 'Créer un atelier',
    vide: 'Aucun atelier. Crée le premier.',
    erreurChargement: 'Impossible de charger les ateliers.',
    erreur: 'Enregistrement impossible.',
    cree: 'Atelier créé.',
    enregistre: 'Atelier enregistré.',
    modifier: 'Modifier',
    publier: 'Publier',
    depublier: 'Dépublier',
    publie: 'Publié',
    brouillon: 'Brouillon',
    enLigne: 'En ligne',
    champs: {
      titre: 'Titre',
      sousTitre: 'Sous-titre',
      date: 'Date et heure',
      description: 'Description',
      descriptionAide: 'Deux phrases : le format, ce que la personne en retire.',
      enLigne: 'En ligne',
      enLigneAide: 'Un atelier en ligne concerne tout le monde, sans filtre de région.',
      lieu: 'Lieu',
      lieuAide: 'La ville, ou « En ligne ».',
      region: 'Région',
      regionAide: 'Pour le filtre des annonces et la carte des personnes concernées.',
      sansRegion: 'Non précisée',
      places: 'Places',
      lien: 'Lien de réservation',
      lienAide: "La réservation se fait chez toi, hors de l'application.",
      recompense: 'Récompense qui donne une place',
      recompenseAide:
        "Optionnel : la récompense de la boutique qui s'échange contre une place ici.",
      sansRecompense: 'Aucune',
      publie: 'Publié',
      publieAide: "Visible dans l'application dès l'enregistrement.",
    },
  },

  utilisateurs: {
    titre: 'Les utilisateurs',
    intro:
      "Les profils, sans adresse e-mail (elle reste dans l'authentification). Suspendre un compte lui coupe l'enregistrement et la boutique ; la personne garde la lecture, la copie de ses données et la suppression.",
    nombre: (n: number) => (n === 1 ? '1 profil' : `${n} profils`),
    rechercher: 'Chercher un prénom ou un identifiant',
    filtres: { tous: 'Tous', suspendus: 'Suspendus', admins: 'Admins' },
    vide: 'Aucun profil dans cette liste.',
    erreurChargement: 'Impossible de charger les profils.',
    erreur: "L'opération n'a pas abouti.",
    sansPrenom: 'Sans prénom',
    admin: 'Admin',
    depuis: (date: string) => `depuis le ${date}`,
    suspenduDepuis: (date: string) => `suspendu le ${date}`,
    suspendre: 'Suspendre',
    reactiver: 'Réactiver',
    suspendreTitre: (nom: string) => `Suspendre ${nom}`,
    suspendreMessage:
      "Le motif est gardé dans le journal, il n'est pas montré à la personne. Elle verra un écran qui dit que son compte est suspendu.",
    motif: 'Motif',
    suspendu: 'Compte suspendu.',
    reactive: 'Compte réactivé.',
  },

  sujets: {
    titre: "Les sujets de l'Arène",
    intro:
      "La banque des sujets, dans leur ordre de passage. Le serveur active le suivant quand la semaine du précédent est finie ; rien ne s'active tant que la banque est vide.",
    creer: 'Créer un sujet',
    vide: 'Aucun sujet dans la banque. Crée le premier.',
    erreurChargement: 'Impossible de charger les sujets.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Un sujet porte déjà cette clé, ou cet ordre.',
    cree: 'Sujet créé.',
    enregistre: 'Sujet enregistré.',
    modifier: 'Modifier',
    duree: (secondes: number) => `${secondes} s de parole`,
    actifDepuis: (date: string) => `actif depuis le ${date}`,
    etats: {
      passe: 'Passé',
      en_cours: 'En cours',
      a_venir: 'À venir',
      inactif: 'Inactif',
    },
    champs: {
      texte: 'Le sujet',
      texteAide: 'La question, telle que les gens la lisent. Une phrase.',
      consigne: 'Consigne',
      consigneAide: 'Optionnel : ce que tu attends du passage, en une ligne.',
      ordre: 'Ordre de passage',
      ordreAide: 'Le serveur prend le plus petit ordre pas encore activé.',
      duree: 'Durée maximale',
      provisoireAide: "Tant que c'est coché, le sujet vient de la maquette et attend ta version.",
      actifAide: 'Un sujet inactif ne sera jamais activé.',
    },
  },

  theses: {
    titre: 'Les thèses du face-à-face',
    intro:
      "La banque des sujets de débat. C'est ce que l'application propose en premier, parce que la plupart des gens à qui on demande d'inventer un sujet se figent ou en choisissent un qu'ils ne savent pas défendre. Rétor défend la thèse ; la personne la contredit.",
    creer: 'Créer une thèse',
    vide: 'Aucune thèse dans la banque. Crée la première.',
    erreurChargement: 'Impossible de charger les thèses.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Une thèse porte déjà cette clé, ou cet ordre.',
    cree: 'Thèse créée.',
    enregistre: 'Thèse enregistrée.',
    modifier: 'Modifier',
    proposees: "Proposées dans l'application",
    proposeesAide: 'Les trois premières thèses actives, dans leur ordre.',
    tons: {
      ferme: 'Ferme',
      provocateur: 'Provocateur',
      academique: 'Académique',
      bienveillant: 'Bienveillant',
    },
    champs: {
      texte: 'La thèse',
      texteAide: 'Une phrase affirmative, que Rétor va défendre et que la personne va contredire.',
      ton: 'Ton de Rétor',
      tonAide: 'Le ton proposé par défaut. La personne peut en choisir un autre.',
      ordre: 'Ordre',
      ordreAide: "L'application propose les premières thèses actives, dans cet ordre.",
      provisoireAide: "Tant que c'est coché, la thèse attend ta version.",
      actifAide: "Une thèse inactive n'est jamais proposée.",
    },
  },

  moderation: {
    titre: 'La modération',
    intro:
      "Sont retirés le contenu sexuel, le harcèlement de personnes réelles et ce qui est illégal. Les sujets difficiles restent : la politique, la religion et l'éthique.",
    tous: 'Toutes',
    vide: 'Rien dans cette liste.',
    erreurChargement: 'Impossible de charger les prises.',
    erreur: "La décision n'a pas pu être enregistrée.",
    traite: 'Décision enregistrée.',
    sansSujet: 'Sujet inconnu',
    audioSupprime: 'audio supprimé',
    publier: 'Publier',
    retirer: 'Retirer',
    retirerTitre: 'Retirer cette prise',
    retirerAide:
      "Le motif est gardé dans le journal. La prise disparaît de l'Arène et son audio est supprimé.",
    motif: 'Motif',
    statuts: {
      en_moderation: 'À relire',
      publiee: 'Publiée',
      retiree: 'Retirée',
    },
    contextes: {
      arene: 'Arène',
      duel: 'Duel',
    },
  },

  exports: {
    titre: 'Les demandes de données',
    intro:
      "Chaque ligne est une personne qui a demandé une copie de ses données (chapitre 2). Tu la prépares et l'envoies par e-mail, puis tu marques la demande traitée.",
    voirTraitees: 'Voir les traitées',
    masquerTraitees: 'Masquer les traitées',
    vide: 'Aucune demande à traiter.',
    erreurChargement: 'Impossible de charger les demandes.',
    erreur: "La demande n'a pas pu être mise à jour.",
    sansEmail: 'Sans adresse',
    traiteeLe: (date: string) => `traitée le ${date}`,
    traitee: 'Traitée',
    aTraiter: 'À traiter',
    marquerTraitee: 'Marquer traitée',
    rouvrir: 'Rouvrir',
    misAJour: 'Demande mise à jour.',
  },
} as const
