// Every user-facing string of the admin lives here (decision 17).
// Plain French, tutoiement, buttons are verbs, messages are information. No aphorism,
// no slogan, no sentence built on a negated opposite ("X, pas Y"), no em dash.
// The writing rules and the checklist are in docs/STRINGS.md.

export const fr = {
  app: {
    nom: 'LEQ',
    sousTitre: 'Administration',
  },

  commun: {
    chargement: 'Chargement en cours.',
    reessayer: 'Réessayer',
    enregistrer: 'Enregistrer',
    annuler: 'Annuler',
    continuer: 'Continuer',
    fermer: 'Fermer',
    modifieLe: (date: string) => `Modifié le ${date}`,
    oui: 'Oui',
    non: 'Non',
  },

  navigation: {
    libelle: 'Navigation principale',
    accueil: 'Accueil',
    configuration: 'Configuration',
    drapeaux: 'Drapeaux',
    defis: 'Défis',
    exercices: 'Exercices',
    recompenses: 'Récompenses',
    echanges: 'Échanges',
    grille: 'Grille',
    annonces: 'Annonces',
    ateliers: 'Ateliers',
    sujets: "Sujets de l'Arène",
    theses: 'Thèses du face-à-face',
    moderation: 'Modération',
    utilisateurs: 'Utilisateurs',
    exports: 'Demandes de données',
    seDeconnecter: 'Se déconnecter',
  },

  connexion: {
    titre: 'Se connecter',
    intro: 'Entre ton adresse e-mail et ton mot de passe.',
    email: 'Adresse e-mail',
    motDePasse: 'Mot de passe',
    valider: 'Se connecter',
    enCours: 'Connexion en cours',
    identifiantsIncorrects: 'Identifiants incorrects.',
    indisponible: 'Connexion impossible pour le moment. Réessaie dans un instant.',
  },

  acces: {
    reserve: "Tu n'as pas accès à l'administration.",
    connecteAvec: (email: string) => `Tu es connecté·e avec ${email}.`,
    verification: 'Vérification de ta session.',
  },

  accueil: {
    titre: 'Accueil',
    intro: "Ce qui t'attend, et ce qu'il reste à écrire.",
    erreurChargement: 'Impossible de charger le tableau de bord.',

    attente: {
      titre: 'Ce qui attend une décision',
      intro: 'Chaque file mène à la page où tu la traites.',
      rien: "Rien ne t'attend pour le moment.",
      moderation: 'Prises à relire',
      echanges: 'Échanges à honorer',
      demandes: 'Demandes de données',
    },

    semaine: {
      titre: 'Cette semaine',
      intro: 'Depuis lundi.',
      prises: 'Prises enregistrées',
      personnes: 'Personnes qui ont parlé',
      defisValides: 'Défis validés',
      comptes: 'Nouveaux comptes',
    },

    etat: {
      titre: "L'état de l'application",
      fonctions: 'Fonctions ouvertes',
      noms: {
        arene: "L'Arène",
        duels: 'Les duels',
        face_a_face: 'Le face-à-face',
      },
      sujet: "Sujet de l'Arène",
      sujetJour: (texte: string, jour: number) => `${texte} · jour ${jour} sur 7`,
      sujetAucun: 'Aucun sujet actif',
      annonces: 'Annonces ce mois-ci',
      annoncesValeur: (envoyees: number, plafond: number) => `${envoyees} sur ${plafond}`,
      grille: 'Grille de Rebecca',
      grillePubliee: 'Publiée',
      grilleAbsente: 'Pas encore publiée',
    },

    ecrire: {
      titre: 'Ce qui attend ton texte',
      intro: "L'application montre encore des textes provisoires. Remplace-les par les tiens.",
      rien: 'Tout le contenu est de toi.',
      defis: 'Défis provisoires',
      exercices: 'Exercices provisoires',
      recompenses: 'Récompenses provisoires',
      sujets: "Sujets de l'Arène",
      theses: 'Thèses du face-à-face',
    },
  },

  configuration: {
    titre: 'Configuration',
    intro: "Une modification s'applique au prochain lancement de l'application.",
    colonnes: {
      cle: 'Clé',
      description: 'Description',
      valeur: 'Valeur',
      actions: 'Actions',
    },
    sections: {
      points: 'Points',
      diagnostic: 'Diagnostic',
      parcours: 'Rythme du parcours',
      serie: 'Série et points',
      arene: 'Arène et duels',
      faceAFace: 'Face-à-face',
      annonces: 'Annonces',
      nettoyage: 'Nettoyage',
      autres: 'Autres',
    },
    vide: "Aucune valeur n'est encore réglée.",
    erreurChargement: 'Impossible de charger la configuration.',
    erreurs: {
      nombre: 'Saisis un nombre.',
      vide: 'Saisis une valeur.',
      json: 'JSON invalide.',
    },
    etats: {
      modifie: 'Modifié, pas encore enregistré.',
      enregistrement: 'Enregistrement',
    },
    rechercher: 'Rechercher un réglage',
    aEnregistrer: (n: number) => (n === 1 ? '1 valeur modifiée' : `${n} valeurs modifiées`),
    toasts: {
      succes: (cle: string) => `Valeur enregistrée : ${cle}.`,
      enregistrees: (n: number) => (n === 1 ? 'Valeur enregistrée.' : `${n} valeurs enregistrées.`),
      erreur: "Enregistrement impossible. Rien n'a été changé.",
      partiel: (ecrites: number, echouees: number) => {
        const sauvees =
          ecrites > 1 ? `${ecrites} valeurs enregistrées` : `${ecrites} valeur enregistrée`
        return `${sauvees}, ${echouees} en échec. Les valeurs en échec sont restées à l'écran.`
      },
    },
    champ: {
      valeurDe: (cle: string) => `Valeur de ${cle}`,
      annulerPour: (cle: string) => `Annuler les changements de ${cle}`,
      enregistrerPour: (cle: string) => `Enregistrer ${cle}`,
    },
  },

  drapeaux: {
    titre: 'Drapeaux',
    intro: 'Une fonction en ligne devient visible par tout le monde au prochain lancement.',
    vide: "Aucune fonction n'est encore réglable ici.",
    erreurChargement: 'Impossible de charger les drapeaux.',
    etats: {
      enLigne: 'En ligne',
      horsLigne: 'Hors ligne',
      absent: 'Absent de la base',
    },
    basculer: (objet: string) => `Mettre ${objet} en ligne ou hors ligne`,
    confirmationTitre: (objet: string) => `Mettre ${objet} en ligne`,
    items: {
      arene: {
        nom: "L'Arène",
        objet: "l'Arène",
        description: 'Le sujet de la semaine, les prises publiques et les votes.',
        confirmation: "L'Arène deviendra visible par tous les utilisateurs. Continuer ?",
      },
      duels: {
        nom: 'Les duels',
        objet: 'les duels',
        description: "Les défis entre deux personnes, avec un verdict rendu par l'analyse.",
        confirmation: 'Les duels deviendront visibles par tous les utilisateurs. Continuer ?',
      },
      face_a_face: {
        nom: 'Le face-à-face',
        objet: 'le face-à-face',
        description: 'Le débat en direct avec Rétor.',
        confirmation: 'Le face-à-face deviendra visible par tous les utilisateurs. Continuer ?',
      },
    },
    toasts: {
      succes: 'Enregistré.',
      erreur: "Enregistrement impossible. L'état précédent est rétabli.",
    },
  },

  banques: {
    formats: {
      standard: 'Défi',
      texte: 'Défi texte',
      long: 'Grand format',
    },
    badges: {
      provisoire: 'Provisoire',
      valide: 'Validé',
      inactif: 'Inactif',
    },
    erreurs: {
      requis: 'Ce champ est obligatoire.',
      nombre: 'Saisis un nombre.',
      entier: 'Saisis un nombre entier.',
      positif: 'Saisis un nombre positif.',
      cle: 'Lettres minuscules, chiffres et tirets bas seulement.',
      texteRequis: 'Un défi texte a besoin de son texte à lire.',
      preparationRequise: 'Un grand format a besoin de sa durée de préparation.',
      bande: 'Le max doit être supérieur ou égal au min.',
      date: 'Choisis une date.',
      contrat: 'Cette valeur ne respecte pas le contrat.',
    },
    champs: {
      cle: 'Clé technique',
      cleAide: 'Écrite à partir du titre. Tu peux la changer ici. Elle ne bouge plus ensuite.',
      titre: 'Titre',
      consigne: 'Consigne',
      consigneAide: 'Ce que la personne lit avant de parler, dans tes mots.',
      competence: 'Compétence travaillée',
      competenceAide: 'Le même mot relie ce défi à ses exercices de rattrapage.',
      provisoire: 'Provisoire',
      provisoireAide:
        "Coché, l'application signale que la consigne attend ta version. Décoche quand le texte est le tien.",
      actif: 'Actif',
      actifAide: "Un défi inactif n'entre plus dans les nouveaux parcours.",
      actifAideExercice: "Un exercice inactif n'est plus proposé.",
    },
  },

  defis: {
    titre: 'Les défis',
    intro:
      "Un titre ou une consigne modifiée s'applique tout de suite. L'ordre et le seuil de réussite ne valent que pour les parcours créés ensuite.",
    creer: 'Créer un défi',
    vide: 'Aucun défi pour le moment. Crée le premier.',
    erreurChargement: 'Impossible de charger les défis.',
    acte: (ordre: number) => `Acte ${ordre}`,
    nombreDefis: (n: number) => (n === 1 ? '1 défi' : `${n} défis`),
    aucunDefi: 'Aucun défi dans cet acte.',
    renommer: 'Renommer',
    ajouterActe: 'Ajouter un acte',
    ajouterDefiIci: 'Ajouter un défi',
    acteTitre: "Titre de l'acte",
    acteSousTitre: 'Sous-titre',
    acteEnregistre: 'Acte enregistré.',
    monter: (titre: string) => `Monter ${titre}`,
    descendre: (titre: string) => `Descendre ${titre}`,
    modifier: 'Modifier',
    resume: (minutes: number, points: number) => `${minutes} min · ${points} pts`,
    seuil: (seuil: string) => `seuil ${seuil}`,
    ordreEchange: 'Ordre modifié.',
    erreurOrdre: "L'ordre n'a pas pu être modifié.",
    edition: {
      titreCreation: 'Nouveau défi',
      titreModification: 'Modifier le défi',
      introuvable: "Ce défi n'existe pas.",
      retour: 'Retour aux défis',
      acte: 'Acte',
      ordre: "Ordre dans l'acte",
      format: 'Format',
      formatAide:
        'Défi : deux minutes de parole. Défi texte : lire un texte, puis le défendre. Grand format : préparer, puis parler cinq minutes.',
      focus: 'Ce que le retour regardera',
      focusAide: 'La personne le lit avant de parler. Un seul point à la fois.',
      dureeMax: 'Durée maximale de parole',
      points: 'Points',
      seuil: 'Seuil de réussite',
      seuilAide:
        'Note totale à atteindre sur la grille. Sans grille publiée, le défi reste ouvert.',
      texte: 'Le texte à lire',
      dureeLecture: 'Durée de lecture estimée',
      preparation: 'Durée de préparation',
      plan: 'Les appuis du plan',
      planAide: 'Affichés pendant la préparation et la prise. Trois en général.',
      appuiTitre: "Titre de l'appui",
      appuiDetail: 'Détail',
      ajouterAppui: 'Ajouter un appui',
      retirerAppui: (n: number) => `Retirer l'appui ${n}`,
      secondes: 's',
      marquerValide: 'Marquer comme validé',
      marquerValideTitre: 'Marquer ce défi comme validé',
      marquerValideMessage:
        "L'application cessera de signaler la consigne comme provisoire. Continuer ?",
      desactiver: 'Désactiver',
      desactiverTitre: 'Désactiver ce défi',
      desactiverMessage:
        "Il n'entrera plus dans les nouveaux parcours. Les personnes qui l'ont déjà le gardent. Continuer ?",
      reactiver: 'Réactiver',
      cree: 'Défi créé.',
      enregistre: 'Défi enregistré.',
      erreur: 'Enregistrement impossible.',
      erreurDoublon: 'Un défi porte déjà cette clé, ou cet ordre dans cet acte.',
    },
  },

  exercices: {
    titre: 'Les exercices',
    intro: 'Proposés après deux échecs sur un défi, avant un troisième essai.',
    creer: 'Créer un exercice',
    vide: 'Aucun exercice pour le moment. Crée le premier.',
    erreurChargement: 'Impossible de charger les exercices.',
    duree: (secondes: number) => `${secondes} s`,
    competence: (competence: string) => `compétence : ${competence}`,
    modifier: 'Modifier',
    nouveau: 'Nouvel exercice',
    modifierTitre: "Modifier l'exercice",
    modification: "Modifier l'exercice",
    dureeChamp: 'Durée',
    cree: 'Exercice créé.',
    enregistre: 'Exercice enregistré.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Un exercice porte déjà cette clé.',
  },

  recompenses: {
    titre: 'Les récompenses',
    intro:
      "Un coût en points par récompense. Mets un plafond mensuel sur celles qui te coûtent de l'argent réel.",
    creer: 'Créer une récompense',
    nouvelle: 'Nouvelle récompense',
    modifierTitre: 'Modifier la récompense',
    vide: 'Aucune récompense pour le moment. Crée la première.',
    erreurChargement: 'Impossible de charger les récompenses.',
    modifier: 'Modifier',
    cout: (points: number) => `${new Intl.NumberFormat('fr-FR').format(points)} pts`,
    sansCout: 'sans coût',
    plafond: (n: number) => (n === 1 ? '1 par mois' : `${n} par mois`),
    sansPlafond: 'sans plafond',
    cree: 'Récompense créée.',
    enregistre: 'Récompense enregistrée.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Une récompense porte déjà cette clé.',
    champs: {
      type: 'Type',
      typeAide:
        "Contenu, réduction et atelier s'échangent contre des points. Une distinction s'attribue, sans coût.",
      ordre: 'Ordre dans la boutique',
      sousTitre: 'Sous-titre',
      image: 'Image',
      imageAide: 'Optionnel. Montrée dans la boutique, sur la carte de la récompense.',
      description: 'Description',
      cout: 'Coût en points',
      plafond: 'Plafond par mois',
      plafondAide:
        "Laisse vide pour ne pas limiter. À remplir dès que la récompense te coûte de l'argent réel.",
      distinctionAide: "Ni coût ni plafond : elle s'attribue, par exemple au n°1 du mois.",
      provisoireAide: "Coché, l'application signale que la récompense attend ta version.",
      actifAide: "Une récompense inactive n'apparaît plus dans la boutique.",
    },
  },

  echanges: {
    titre: 'Les échanges',
    intro: "Contacte la personne, puis marque l'échange honoré. L'annuler lui rend ses points.",
    tous: 'Tous',
    vide: 'Aucun échange dans cette liste.',
    erreurChargement: 'Impossible de charger les échanges.',
    par: (prenom: string) => `par ${prenom}`,
    sansPrenom: 'une personne sans prénom',
    honorer: 'Honorer',
    annuler: 'Annuler',
    annulerTitre: 'Annuler cet échange',
    annulerMessage: (titre: string, points: number) =>
      `${titre} : les ${new Intl.NumberFormat('fr-FR').format(points)} points reviennent à la personne. Continuer ?`,
    traite: 'Échange mis à jour.',
    erreur: "L'échange n'a pas pu être mis à jour.",
    statuts: {
      a_traiter: 'À traiter',
      honore: 'Honoré',
      annule: 'Annulé',
    },
  },

  grille: {
    nouveauCritere: 'Nouveau critère',
    modifierTitre: 'Modifier le critère',
    titre: 'La grille',
    intro:
      'Un brouillon se modifie critère par critère. Une fois publiée, une version ne bouge plus et note toutes les nouvelles prises.',
    vide: 'Aucune version pour le moment. Crée la première pour écrire tes critères.',
    erreurChargement: 'Impossible de charger la grille.',
    erreur: 'Enregistrement impossible.',
    premiereVersion: 'Créer la première version',
    nouvelleVersionDepuis: (v: number) => `Nouvelle version à partir de la ${v}`,
    version: (v: number) => `Version ${v}`,
    versionCreee: (v: number) => `Version ${v} créée, en brouillon.`,
    publieeLe: (date: string) => `publiée le ${date}`,
    publieeCourte: 'Publiée',
    brouillon: 'Brouillon',
    enService: 'En service pour les nouvelles prises',
    nbCriteres: (n: number) => (n === 1 ? '1 critère' : `${n} critères`),
    nbElements: (n: number) => (n === 1 ? '1 mesure' : `${n} mesures`),
    surMax: (max: number) => `sur ${max}`,
    lectureSeule:
      'Une version publiée ne se modifie plus. Crée une nouvelle version pour changer un critère.',
    ajouterCritere: 'Ajouter un critère',
    aucunCritere: 'Aucun critère dans cette version.',
    modifier: 'Modifier',
    supprimer: 'Supprimer',
    supprimerTitre: (nom: string) => `Supprimer le critère « ${nom} »`,
    supprimerMessage:
      'Il disparaît de ce brouillon. Les versions publiées ne changent pas. Continuer ?',
    publier: 'Publier cette version',
    publierTitre: (v: number) => `Publier la version ${v}`,
    publierMessage:
      'Chaque nouvelle prise sera notée avec cette version, et le défi du jour se validera sur ses notes. Une version publiée ne se dépublie pas. Continuer ?',
    publiee: 'Version publiée. Elle note les prochaines prises.',
    critereEnregistre: 'Critère enregistré.',
    critereSupprime: 'Critère supprimé.',
    champs: {
      cle: 'Clé technique',
      cleAide: 'En minuscules, sans espace. Elle nomme la sous-note dans chaque retour.',
      nom: 'Nom montré',
      scoreMax: 'Note maximale',
      scoreMaxAide: 'La somme des notes maximales des critères fait la note totale de la grille.',
      source: 'Comment cet axe est noté',
      sourceAide:
        "Mesuré\u00a0: la machine le calcule sur l'enregistrement. Jugé\u00a0: le modèle le note contre tes deux exemples.",
      sourceMesure: "Mesuré sur l'enregistrement",
      sourceJugement: 'Jugé contre tes exemples',
      exemples: 'Tes deux exemples',
      exemplesAide:
        "Ils tiennent la note en place d'une prise à l'autre. Sans eux, le modèle note contre sa propre idée d'un bon orateur.",
      exempleCinq: 'Une prestation qui vaut cinq sur cet axe',
      exempleDeux: 'Une prestation qui vaut deux sur cet axe',
      definition: 'Définition',
      definitionAide: 'En une phrase, montrée à côté du nom.',
      elements: 'Les mesures écoutées',
      elementsAide:
        'La note du critère est la moyenne pondérée des bandes, ramenée à la note maximale.',
      mesure: 'Mesure',
      mesureAide: "Le chiffre de l'analyse que ce critère écoute.",
      parType: 'un mot béquille précis…',
      mot: 'Le mot',
      poids: 'Poids',
      poidsAide: "Une mesure de poids 2 compte deux fois plus qu'une mesure de poids 1.",
      bandes: 'Les bandes',
      bandesAide:
        'De min inclus à max exclu. Laisse min ou max vide pour une bande ouverte ; une valeur hors de toute bande vaut 0.',
      min: 'min',
      max: 'max',
      score: 'note',
      ajouterBande: 'Ajouter une bande',
      retirerBande: (n: number) => `Retirer la bande ${n}`,
      ajouterElement: 'Ajouter une mesure',
      retirerElement: 'Retirer cette mesure',
    },
  },

  annonces: {
    titre: 'Les annonces',
    intro:
      'Deux annonces par mois au plus. Choisis des régions pour un atelier en salle, aucune pour un atelier en ligne.',
    compteur: (n: number, plafond: number) => `${n} sur ${plafond} ce mois-ci`,
    envoyer: 'Envoyer maintenant',
    apercu: 'Aperçu',
    apercuTitre: 'Le titre de ton annonce',
    apercuCorps: 'Tel que les gens le liront sur leur écran verrouillé.',
    apercuAide: "Une annonce ne se rattrape pas. Relis-la avant d'envoyer.",
    envoyee: 'Annonce envoyée. Elle arrivera sur les téléphones dans les prochaines minutes.',
    plafondAtteint:
      'Le plafond du mois est atteint. La prochaine annonce attendra le mois prochain.',
    erreur: "L'annonce n'a pas été envoyée.",
    erreurChamp: 'Vérifie ce champ.',
    erreurChargement: 'Impossible de charger les annonces.',
    historique: 'Envoyées',
    vide: 'Aucune annonce envoyée pour le moment.',
    videTexte: 'Tes annonces apparaîtront ici, avec le nombre de personnes touchées.',
    toutLeMonde: 'Tout le monde',
    nbRegions: (n: number) => (n === 1 ? '1 région' : `${n} régions`),
    enCours: 'Envoi en cours',
    bilan: (envoyes: number, destinataires: number, echecs: number) =>
      echecs === 0
        ? `${envoyes} sur ${destinataires} reçues`
        : `${envoyes} sur ${destinataires} reçues, ${echecs} en échec`,
    champs: {
      titre: 'Titre',
      titreAide:
        'Assez court pour tenir sur un écran verrouillé. Par exemple : « Rebecca ouvre un atelier ».',
      corps: 'Message',
      corpsAide: "L'atelier, la date et les places, sur le ton d'une invitation.",
      atelier: 'Atelier lié',
      atelierAide:
        "Optionnel. L'application ouvrira sa fiche quand la personne touchera la notification.",
      sansAtelier: 'Aucun',
      regions: 'Régions',
      image: 'Image',
      imageAide: "Optionnel. Elle apparaît dans la notification et sur la fiche de l'atelier.",
      regionsAide:
        "Sans région cochée, l'annonce part à tout le monde. Pour un atelier en salle, coche sa région et les voisines.",
    },
  },

  ateliers: {
    titre: 'Les ateliers',
    intro: "Un atelier publié apparaît dans l'application. Un brouillon reste ici.",
    creer: 'Créer un atelier',
    modifierTitre: "Modifier l'atelier",
    vide: 'Aucun atelier. Crée le premier.',
    erreurChargement: 'Impossible de charger les ateliers.',
    erreur: 'Enregistrement impossible.',
    cree: 'Atelier créé.',
    enregistre: 'Atelier enregistré.',
    modifier: 'Modifier',
    publier: 'Publier',
    depublier: 'Dépublier',
    publie: 'Publié',
    brouillon: 'Brouillon',
    enLigne: 'En ligne',
    champs: {
      titre: 'Titre',
      sousTitre: 'Sous-titre',
      date: 'Date et heure',
      description: 'Description',
      image: 'Image',
      imageAide: "Optionnel. Montrée dans l'application, sur la carte de l'atelier.",
      descriptionAide: 'Deux phrases : le format, et ce que la personne en retire.',
      enLigne: 'En ligne',
      enLigneAide: 'Un atelier en ligne concerne tout le monde, sans filtre de région.',
      lieu: 'Lieu',
      lieuAide: 'La ville, ou « En ligne ».',
      region: 'Région',
      regionAide: 'Sert à filtrer les annonces par région.',
      sansRegion: 'Non précisée',
      places: 'Places',
      lien: 'Lien de réservation',
      lienAide: "La réservation se fait chez toi, hors de l'application.",
      recompense: 'Récompense qui donne une place',
      recompenseAide: "Optionnel. La récompense de la boutique qui s'échange contre une place ici.",
      sansRecompense: 'Aucune',
      publie: 'Publié',
      publieAide: "Visible dans l'application dès l'enregistrement.",
    },
  },

  utilisateurs: {
    titre: 'Les utilisateurs',
    intro:
      "Suspendre un compte coupe l'enregistrement et la boutique. La personne garde ses données et peut les supprimer.",
    nombre: (n: number) => (n === 1 ? '1 profil' : `${n} profils`),
    rechercher: 'Chercher un prénom ou un identifiant',
    filtres: { tous: 'Tous', suspendus: 'Suspendus', admins: 'Admins' },
    vide: 'Aucun profil dans cette liste.',
    erreurChargement: 'Impossible de charger les profils.',
    erreur: "L'opération n'a pas abouti.",
    sansPrenom: 'Sans prénom',
    admin: 'Admin',
    depuis: (date: string) => `depuis le ${date}`,
    suspenduDepuis: (date: string) => `suspendu le ${date}`,
    suspendre: 'Suspendre',
    reactiver: 'Réactiver',
    suspendreTitre: (nom: string) => `Suspendre ${nom}`,
    suspendreMessage:
      'Le motif reste interne. La personne verra seulement que son compte est suspendu.',
    motif: 'Motif',
    suspendu: 'Compte suspendu.',
    reactive: 'Compte réactivé.',
  },

  sujets: {
    titre: "Les sujets de l'Arène",
    intro:
      "Un sujet par semaine, dans cet ordre. Le suivant s'active quand la semaine du précédent est finie.",
    creer: 'Créer un sujet',
    modifierTitre: 'Modifier le sujet',
    vide: 'Aucun sujet pour le moment. Crée le premier.',
    erreurChargement: 'Impossible de charger les sujets.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Un sujet porte déjà cette clé, ou cet ordre.',
    cree: 'Sujet créé.',
    enregistre: 'Sujet enregistré.',
    modifier: 'Modifier',
    duree: (secondes: number) => `${secondes} s de parole`,
    actifDepuis: (date: string) => `actif depuis le ${date}`,
    prevu: 'Jour de passage',
    prevuAide: "Le sujet passe en premier à partir de ce jour. Vide\u00a0: il suit l'ordre.",
    prevuLe: (jour: string) => `prévu le ${jour}`,
    filtreEtat: 'Filtrer par état',
    filtreTous: 'Tous',
    etats: {
      passe: 'Passé',
      en_cours: 'En cours',
      a_venir: 'À venir',
      inactif: 'Inactif',
    },
    champs: {
      prevu: 'Jour de passage',
      prevuAide: "Le sujet passe en premier à partir de ce jour. Vide : il suit l'ordre.",
      texte: 'Le sujet',
      texteAide: 'La question, en une phrase, telle que les gens la liront.',
      consigne: 'Consigne',
      consigneAide: 'Optionnel. Ce que tu attends du passage, en une ligne.',
      ordre: 'Ordre de passage',
      ordreAide: 'Le prochain sujet activé sera le plus petit ordre pas encore passé.',
      duree: 'Durée maximale',
      provisoireAide: 'Coché, le sujet attend ta version.',
      actifAide: 'Un sujet inactif ne sera jamais activé.',
    },
  },

  media: {
    deposer: 'Dépose une image, ou choisis un fichier',
    formats: 'JPEG, PNG, WebP ou AVIF, 5 Mo au maximum',
    envoi: 'Envoi en cours',
    remplacer: 'Remplacer',
    retirer: 'Retirer',
    refusType: "Ce format n'est pas accepté. Choisis un JPEG, un PNG, un WebP ou un AVIF.",
    refusTaille: 'Cette image dépasse 5 Mo. Choisis-en une plus légère.',
    erreur: "L'image n'a pas pu être envoyée.",
  },

  etats: {
    rechercher: 'Rechercher',
    resultats: (n: number) => (n === 1 ? '1 résultat' : `${n} résultats`),
    aucunResultat: 'Aucun résultat',
    aucunResultatTexte: 'Aucune ligne ne correspond à cette recherche.',
  },

  theses: {
    titre: 'Les thèses du face-à-face',
    intro:
      "Rétor défend la thèse, la personne la contredit. Les premières de la liste sont proposées dans l'application.",
    creer: 'Créer une thèse',
    creerAide: 'Rétor défendra cette thèse ; la personne la contredira.',
    modifierTitre: 'Modifier la thèse',
    vide: 'Aucune thèse pour le moment. Crée la première.',
    erreurChargement: 'Impossible de charger les thèses.',
    erreur: 'Enregistrement impossible.',
    erreurDoublon: 'Une thèse porte déjà cette clé, ou cet ordre.',
    cree: 'Thèse créée.',
    enregistre: 'Thèse enregistrée.',
    modifier: 'Modifier',
    proposees: "Proposées dans l'application",
    proposeesAide: 'Les trois premières thèses actives, dans leur ordre.',
    tons: {
      ferme: 'Ferme',
      provocateur: 'Provocateur',
      academique: 'Académique',
      bienveillant: 'Bienveillant',
    },
    champs: {
      texte: 'La thèse',
      texteAide: 'Une phrase affirmative, que Rétor va défendre et que la personne va contredire.',
      ton: 'Ton de Rétor',
      tonAide: 'Le ton proposé par défaut. La personne peut en choisir un autre.',
      ordre: 'Ordre',
      ordreAide: "L'application propose les premières thèses actives, dans cet ordre.",
      provisoireAide: 'Coché, la thèse attend ta version.',
      actifAide: "Une thèse inactive n'est jamais proposée.",
    },
  },

  moderation: {
    titre: 'La modération',
    intro:
      "Retire le contenu sexuel, le harcèlement de personnes réelles et ce qui est illégal. La politique, la religion et l'éthique restent.",
    tous: 'Toutes',
    vide: 'Rien dans cette liste.',
    erreurChargement: 'Impossible de charger les prises.',
    erreur: "La décision n'a pas pu être enregistrée.",
    traite: 'Décision enregistrée.',
    sansSujet: 'Sujet inconnu',
    audioSupprime: 'audio supprimé',
    publier: 'Publier',
    retirer: 'Retirer',
    retirerTitre: 'Retirer cette prise',
    retirerAide: "Le motif reste interne. La prise disparaît de l'Arène et son audio est supprimé.",
    motif: 'Motif',
    statuts: {
      en_moderation: 'À relire',
      publiee: 'Publiée',
      retiree: 'Retirée',
    },
    contextes: {
      arene: 'Arène',
      duel: 'Duel',
    },
  },

  exports: {
    titre: 'Les demandes de données',
    intro: 'Prépare la copie, envoie-la par e-mail, puis marque la demande traitée.',
    voirTraitees: 'Voir les traitées',
    masquerTraitees: 'Masquer les traitées',
    vide: 'Aucune demande à traiter.',
    erreurChargement: 'Impossible de charger les demandes.',
    erreur: "La demande n'a pas pu être mise à jour.",
    sansEmail: 'Sans adresse',
    traiteeLe: (date: string) => `traitée le ${date}`,
    traitee: 'Traitée',
    aTraiter: 'À traiter',
    marquerTraitee: 'Marquer traitée',
    rouvrir: 'Rouvrir',
    misAJour: 'Demande mise à jour.',
  },
} as const
